// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbmQhm8mkHuuqju_GYq7nr8_4n0BpC08U',
    appId: '1:949289792362:web:98a17c278af3c6faf46b13',
    messagingSenderId: '949289792362',
    projectId: 'adaptive-commerce',
    authDomain: 'adaptive-commerce.firebaseapp.com',
    storageBucket: 'adaptive-commerce.firebasestorage.app',
    measurementId: 'G-V5P4NRHNP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBscw9mTdoTSe5wZ2RW0s3BOGwXyypzEuc',
    appId: '1:949289792362:android:c5cfaf33c357ac37f46b13',
    messagingSenderId: '949289792362',
    projectId: 'adaptive-commerce',
    storageBucket: 'adaptive-commerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgnrPykyrL88N2qZ-HdfWkCRoFWcwA-TY',
    appId: '1:949289792362:ios:8c11ff17f4d05a4af46b13',
    messagingSenderId: '949289792362',
    projectId: 'adaptive-commerce',
    storageBucket: 'adaptive-commerce.firebasestorage.app',
    iosBundleId: 'com.example.financeAiAssistant',
  );
}
